    <?php include( 'inc/header.php'); ?>
    <div class="container">
      <div class="row">
        <div class="privacy-terms">
            <h1>Privacy Policy</h1>
            <h3>Effective Date: May 28, 2014<br />
            Introduction</h3>
            <p>Thank you for visiting <u><a class="home-link alias-span" href=""></a></u> a site run by Student loan assistances X. Student loan assistances X ("we", "us") is committed to protecting the privacy of your personally identifiable information. We provide this privacy policy ("Privacy Policy") in order to explain our online information practices and the choices you can make about the way your information is used by us. You must agree to this Privacy Policy, in its entirety, including our use of cookies. Your acceptance of both this Privacy Policy and our use of cookies on the Site shall be deemed a blanket acceptance of such Privacy Policy and cookie usage. If you do not agree to this Privacy Policy in its entirety, you are not authorized to use <u><a class="home-link alias-span" href=""></a></u> </p>
            <h3>Personally Identifiable Information</h3>
            <p>We collect personally identifiable information when you provide it through our form on <u><a class="home-link alias-span" href=""></a></u> Personally identifiable information is any information that can be used to identify or locate a particular person or entity. This may include, but is not limited to: your name, contact information, and information about your job needs. For purposes of this Privacy Policy, your account information shall be considered "Sensitive Information," and will only be shared with student loan assistance providers for purposes of offering you information on student loan assistance.</p>
            <h3>Non-Personally Identifiable Information</h3>
            <p>We may collect certain non-personally identifiable information about you when you visit certain pages of this Site such as the type of browser you are using (e.g., Safari, Internet Explorer), the type of operating system you are using, (e.g., Windows '98 or Mac OS) and the domain name of your Internet service provider (e.g., America Online, Earthlink), and share such information with our Third Party Agent. We use the non-personally identifiable information that we collect to improve the design and content of the Site and to enable us to personalize your Internet experience. We also may use this information in the aggregate to analyze Site usage.</p>
            <h3>Cookies and Web Beacons</h3>
            <p>We use Cookies and Web Beacons to enhance your experience with the Site. You are not authorized to use the services offered on <span class="alias-span"></span> if you do not agree to our use of cookies. For more specific information on the cookies we use, please see Exhibit A, below. Cookies are small packets of data stored on your computer. Cookies are used by your computer's browser to store your preferences. Cookies, by themselves, do not tell us your e-mail address or other personally identifiable information. We use cookies to understand Site usage and to improve the content and offerings on the Site. You may set your browser to warn you that cookies are in use, or to block the use of cookies. Most browsers are set to accept cookies. If your browser is not set to accept cookies, certain uses of the Site may require you to go to your browser user preferences to enable cookies. Each browser is different, so check the "Help" menu of your browser to learn how to change your cookie preferences. If you change computers, operating systems or browsers, or use multiple computers or browsers, you will need to repeat this process for each computer and each browser. To find out more about cookies, please visit <u>www.cookiecentral.com</u> We may additionally collect information using Web beacons, which are commonly referred to in the industry as web bugs, pixel tags or Clear GIFs. Web beacons are electronic images that may be used on the Site, or in our emails to deliver cookies, count visits and determine if an email has been opened and acted upon.</p>
            <h3>Use of Information</h3>
            <p>We use your personally identifiable information: (a) to offer you information on student loan assistance; (b) to track your compliance with the Terms and Conditions ("Terms and Conditions"); and/or (c) for validation, suppression, content improvement and feedback purposes.</p>
            <h3>Information Sharing</h3>
            <p>As a general rule, and other than in connection with the limited exceptions set forth below, we will not sell, share or rent your personally identifiable information to or with others. Notwithstanding the foregoing, we may, from time to time, provide such information to certain third-party administrative vendors for efficiency purposes in providing administrative or program management services in connection with your Account. Any third-party vendor so used has agreed to protect the confidentiality of information provided by us. Further, we reserve the right to share your personally identifiable information: (a) where required by law, or requested by a court of competent jurisdiction; (b) in the event of any reorganization, merger, sale, joint venture, assignment, transfer or other disposition of all or any portion of our business, assets or stock; (c) where you are in violation of this Privacy Policy, the Terms and Conditions and/or Services Agreement; (d) in the case of a dispute; or (e) where we determine, in our sole discretion, that such disclosure is necessary to protect our rights and/or a third party, or necessary to protect us from liability of any kind. The aforementioned includes exchanging information with other companies and organizations for fraud protection.</p>
            <h3>Data Retention</h3>
            <p>Subject to any mandatory obligations to delete data, your information may be retained by us and in our agent portal, server logs, databases and records indefinitely.</p>
            <h3>Third Party Links</h3>
            <p>The Site may contain links to third-party websites ("Third Party Websites"). Please be aware that we are not responsible for the privacy practices of Third Party Websites. We encourage you to be aware when you leave the Site and to read the privacy policies of each and every website that collects personally identifiable information. This Privacy Policy applies solely to information collected by the Site.</p>
            <h3>Minors</h3>
            <p>We encourage parents and guardians to spend time online with their children and to participate and monitor the interactive activities of their children. We will never knowingly collect any personal information about individuals under eighteen (18) years of age. If we obtain actual knowledge that we have collected personal information about an individual under eighteen (18) years of age, that information will be immediately deleted from our database.</p>
            <h3>Security</h3>
            <p>We take appropriate security measures (including physical, electronic, and procedural measures) to help safeguard your personal information from unauthorized access and disclosure. For example, with regard to <u><a class="home-link alias-span" href=""></a></u> internal operations, only authorized employees and authorized third party service providers are permitted to access personal information, and they may do so only for permitted business functions. We follow generally accepted industry standards to protect the personal information submitted to us, both during transmission and once we receive it. No method of transmission over the Internet, or method of electronic storage, is 100% secure, however. Therefore, we cannot guarantee its absolute security.</p>
            <p>We may provide this information in a standardized format that is not specific to you. The designated e-mail address for these requests is privacy@<span class="alias-span"></span> Please note that we are only required to respond to one request per customer each year, and we are not required to respond to requests made by means other than through this e-mail address or mailing address. Please also be aware that not all information sharing is covered by the California requirements and only information on covered sharing will be included in our response.</p>
            <h3>Opting Out of Receiving E-mail</h3>
            <p>You may at any time choose to stop receiving emails containing general information regarding Student loan assistance by following the instructions at the end of each such email or by contacting privacy@<span class="alias-span"></span> Should you be contacted by us through email, you can follow the instructions at the end of each such email to stop receiving such emails. There may be a short delay of up to several business days while your request is being verified, deployed and processed across our servers. Notwithstanding the foregoing, we may continue to contact you for the purpose of responding to any inquiry or request made by you.</p>
            <h3>International Users</h3>
            <p>This Privacy Policy is intended to cover collection of information on our website from residents of the United States. If you are visiting our website from outside the United States, please be aware that your information may be transferred to, stored and processed in the United States where our servers are located and our central database is operated. The data protection and other laws of the United States and other countries might not be as comprehensive as those in your country. Please be assured that we seek to take reasonable steps to ensure that your privacy is protected. By using our services, you understand that your information may be transferred to our facilities and those third parties with whom we share it as described in this privacy policy. By using our website and the services available on the site, which are provided exclusively from the United States, you hereby consent to the transfer of your information to the United States and its collection, storage, sharing and use as described in this Privacy Policy. You further agree that all transactions relating to the site and our services shall be deemed to have occurred in the United States.</p>
            <h3>Notification of Changes</h3>
            <p>We reserve the right to change or update this Privacy Policy at any time by posting a clear and conspicuous notice on the Site explaining that we are changing our Privacy Policy. All Privacy Policy changes will take effect immediately upon their posting on the Site. Please check the Site periodically for any changes. Your continued use of the Site and/or acceptance of our e-mail communications following the posting of changes to this Privacy Policy will constitute your acceptance of any and all changes.</p>
        </div>
      </div>
    </div>
    <?php include('inc/footer.php'); ?>

    <script type="text/javascript">   
        $('.home-link').attr('href', window.location.origin);
    </script>
    
  </body>

</html>